export enum Route {
  HOME = '/',

  DASHBOARD = '/skill-map',

  AUTH_LOGIN = '/auth/login',
  AUTH_EMAIL = '/auth/email',
  AUTH_THAID = '/auth/thaid',
  AUTH_GOOGLE_SIGN_IN = '/auth/google/sign-in',
  AUTH_GOOGLE_CONSENT = '/auth/google/consent',
  AUTH_VERIFY = '/auth/verify',
  AUTH_CONSENT = '/auth/consent',

  RIASEC_LANDING = '/RIASEC',

  JOURNEY = '/journey',
  JOURNEY_STEP = '/journey/:step',

  CAREER_EXPLORER = '/skill-trends',
  CAREER_DETAIL = '/skill-trends/:id',
  CAREER_GOAL = '/career-goal/:id',

  COURSE = '/skill-builder',
  COURSE_CATEGORY = '/skill-builder/category/:category',
  COURSE_DETAIL = '/skill-builder/:id',
  COURSE_CHECKOUT = '/skill-builder/:id/checkout',
  COURSE_LESSON = '/skill-builder/:id/lessons/:lessonId',
  COURSE_COMPLETE = '/skill-builder/:id/complete',
  COURSE_QUIZ_RESULT = '/skill-builder/:id/quiz/:quizId/result',

  MY_SKILLS = '/my-skills',

  MY_PROFILE = '/my-profile',
  MY_CREDIT = '/my-credit',

  PORTFOLIO_CREATE = '/portfolio/create',
  PORTFOLIO_PREVIEW = '/portfolio/:id/preview',

  INTERVIEW_PREP = '/interview-prep',
  INTERVIEW_INTRO = '/interview-prep/:role',
  INTERVIEW_SESSION = '/interview-prep/:role/session',
  INTERVIEW_RESULT = '/interview-prep/:role/session/:id/result',

  RIASEC_TEST = '/RIASEC/test',
  RIASEC_TEST_RESULT = '/RIASEC/test/result/:resultId',
  RIASEC_TEST_HISTORY = '/RIASEC/test/result/history',

  JOBS = '/jobs',
  JOB_DETAIL = '/jobs/:id',
  JOB_APPLY = '/jobs/:id/apply',
  JOB_APPLY_SUCCESS = '/jobs/:id/apply/success',

  FILES = '/files',
  COMMUNITY = '/opportunity-hub',
  COMMUNITY_CATEGORY = '/opportunity-hub/category/:category',
  COMMUNITY_POST_DETAIL = '/opportunity-hub/:postId',

  DESIGN_SYSTEM = '/design-system',
  DESIGN_SYSTEM_ACCORDION = '/design-system/accordion',
  DESIGN_SYSTEM_ALERT = '/design-system/alert',
  DESIGN_SYSTEM_BADGE = '/design-system/badge',
  DESIGN_SYSTEM_BREADCRUMB = '/design-system/breadcrumb',
  DESIGN_SYSTEM_BUTTONS = '/design-system/buttons',
  DESIGN_SYSTEM_CARD = '/design-system/card',
  DESIGN_SYSTEM_CHECKBOX = '/design-system/checkbox',
  DESIGN_SYSTEM_CHIP = '/design-system/chip',
  DESIGN_SYSTEM_COURSE_CARD = '/design-system/course-card',
  DESIGN_SYSTEM_DIALOG = '/design-system/dialog',
  DESIGN_SYSTEM_EMPTY_BUTTON = '/design-system/empty-button',
  DESIGN_SYSTEM_INPUT = '/design-system/input',
  DESIGN_SYSTEM_LABEL = '/design-system/label',
  DESIGN_SYSTEM_LINK = '/design-system/link',
  DESIGN_SYSTEM_PAGINATION = '/design-system/pagination',
  DESIGN_SYSTEM_PROGRESS = '/design-system/progress',
  DESIGN_SYSTEM_PROGRESS_RING = '/design-system/progress-ring',
  DESIGN_SYSTEM_RADIO = '/design-system/radio',
  DESIGN_SYSTEM_RATING = '/design-system/rating',
  DESIGN_SYSTEM_SECTION_NAV = '/design-system/section-nav',
  DESIGN_SYSTEM_SELECT = '/design-system/select',
  DESIGN_SYSTEM_SEPARATOR = '/design-system/separator',
  DESIGN_SYSTEM_SHEET = '/design-system/sheet',
  DESIGN_SYSTEM_SKELETON = '/design-system/skeleton',
  DESIGN_SYSTEM_SKILL = '/design-system/skill',
  DESIGN_SYSTEM_SPEECH_BUBBLE = '/design-system/speech-bubble',
  DESIGN_SYSTEM_SWITCH = '/design-system/switch',
  DESIGN_SYSTEM_TABS = '/design-system/tabs',
  DESIGN_SYSTEM_TAG = '/design-system/tag',
  DESIGN_SYSTEM_TOOLTIP = '/design-system/tooltip',
}
